/**
 * Runtime schema constants extracted from apps/api/openapi.json.
 *
 * AUTO-GENERATED by scripts/generate-constants.mjs (run via `pnpm gen:api`) — DO NOT EDIT.
 * These mirror numeric OpenAPI constraints (e.g. array `maxItems`) that the generated
 * TypeScript types in `schema.ts` cannot carry at runtime. A CI drift check fails the PR if
 * this file is stale, so the values always match the committed backend contract.
 */

/** Numeric limits the API enforces, surfaced for client-side validation. */
export const schemaLimits = {
  /**
   * Maximum number of words accepted by `POST /generate` in a single request
   * (`GenerateRequest.words.maxItems`). The server rejects more with HTTP 422.
   */
  generateWordsMaxItems: 30,
  /**
   * Bounds + default for the number of new words `POST /discover` previews in one request
   * (`DiscoverRequest.count` minimum/maximum/default). The Discover form clamps to these and
   * falls back to the default when the user has no saved `discover_count` preference.
   */
  discoverCountMin: 1,
  discoverCountMax: 20,
  discoverCountDefault: 5,
} as const;
