/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Account
         * @description Hard-delete the authenticated user's account (auth user + cascaded domain data).
         */
        delete: operations["delete_account_account_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/account/deletion-confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm Account Deletion
         * @description Complete a public account deletion: verify the emailed token, then cascade-delete the account.
         *
         *     A malformed / tampered / expired token → ``400`` (a generic "invalid or expired" message, never
         *     distinguishing which). A verified token runs the same hard delete as ``DELETE /account``; a
         *     backend failure surfaces ``502`` (retryable), never a false success.
         */
        post: operations["confirm_account_deletion_account_deletion_confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/account/deletion-request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request Account Deletion
         * @description Start a public account deletion: email a confirmation link if the address has an account.
         *
         *     Always returns the same generic acknowledgement (no account enumeration). Rate-limited per email
         *     to prevent using the form to bomb an inbox with deletion mail.
         */
        post: operations["request_account_deletion_account_deletion_request_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/account/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Account
         * @description Return the authenticated user's full data bundle (scoped to ``current_user``).
         */
        get: operations["export_account_account_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cards/save": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Save Cards
         * @description Persist generated recognition+production previews into the current user's deck (saved).
         */
        post: operations["save_cards_cards_save_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/discover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Discover
         * @description Preview new words at the learner's level, excluding vocabulary they already know.
         *
         *     Cache-aware (task 3.6.3): a repeat for the same ``(language, topic, count)`` within the reuse
         *     window is served from ``cache`` — no provider call, no gate, no count. The ``guard`` is handed
         *     to the service so the per-user daily ``discover`` cap is enforced (and counted) only on a cache
         *     miss, where the provider call runs under the global concurrency cap (``limiter``). An explicit
         *     reroll (``body.fresh``) bypasses the cache so it returns a freshly generated, counted set rather
         *     than replaying the identical cached preview (finding S8).
         */
        post: operations["discover_discover_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/discover/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Accept
         * @description Generate and save cards for the accepted ``words`` (delegates to the generate flow).
         *
         *     Accepting reuses the generate path, so it is gated and counted as ``generate`` (not
         *     ``discover``). The ``guard`` is handed to the service so the spend is counted right after the
         *     provider call and **before** the card persistence — a save failure then still counts the billed
         *     call (closing the billed-but-uncounted window) instead of skipping the increment. The id passed
         *     to the increment is always the JWT-derived ``user_id`` (never client-supplied).
         */
        post: operations["accept_discover_accept_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/explain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Explain
         * @description Explain a tapped word in a sentence (served from the card's cache when available).
         *
         *     The ``guard`` is built **unchecked** and handed to ``ExplainService`` so the per-user daily
         *     ``explain`` cap is enforced (and counted) only on a cache miss — a cache hit stays free. On a
         *     miss the provider call runs under the global concurrency cap (``limiter``).
         */
        post: operations["explain_explain_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feature-flags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Feature Flags
         * @description Return the resolved PUBLIC feature-flag map (``{name: enabled}``, no secrets).
         */
        get: operations["read_feature_flags_feature_flags_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate
         * @description Generate recognition+production card previews for ``words`` (nothing is persisted yet).
         *
         *     The ``quota_guard`` dependency enforces the per-user daily ``generate`` cap before the provider
         *     is called; on success we count the spend — but only when the call produced cards, so a no-op
         *     empty/blank-only request never burns a daily count (S11). The provider call runs under the
         *     global concurrency cap (``limiter``).
         */
        post: operations["generate_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe used by Cloud Run and CI smoke checks.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/languages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Languages
         * @description List the current user's languages, oldest first.
         */
        get: operations["list_languages_languages_get"];
        put?: never;
        /**
         * Add Language
         * @description Add a language (idempotent on the per-user ``UNIQUE (user_id, name)``).
         *
         *     The response ``created`` flag is ``True`` when a new language was inserted and ``False`` when
         *     the name already existed — in which case the existing row is returned unchanged, so a client
         *     can tell a fresh add from a re-add (and skip resetting an existing language's proficiency).
         *     Status stays 200 (the API's ``POST`` convention); the flag carries the signal.
         */
        post: operations["add_language_languages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/languages/{language_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove Language
         * @description Delete a language (its cards/proficiency cascade).
         */
        delete: operations["remove_language_languages__language_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Language
         * @description Edit a language's fields (``name`` / ``code`` / ``vowelized``); a partial update.
         *
         *     Only the fields present in the body are changed (``code`` may be sent as ``null`` to clear it).
         */
        patch: operations["update_language_languages__language_id__patch"];
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Me
         * @description Return the authenticated user's identity, plan, and per-language proficiency levels.
         */
        get: operations["read_me_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/proficiency/{language_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Proficiency
         * @description Return the learner's level for one of their languages.
         */
        get: operations["get_proficiency_proficiency__language_id__get"];
        /**
         * Set Proficiency
         * @description Override the level by raw ``score`` or CEFR ``band`` (exactly one; enforced by the DTO).
         */
        put: operations["set_proficiency_proficiency__language_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ready
         * @description Readiness probe: ``200 {"status":"ready"}`` when the DB answers, else ``503``.
         *
         *     Unauthenticated like ``/health``, but where the pure liveness probe does no I/O, ``/ready``
         *     verifies database connectivity with a lightweight ``SELECT 1`` on a PLAIN (RLS-free) engine
         *     connection — no JWT, never the ``authenticated`` role (see
         *     :func:`app.db.session.check_db_ready`). Cloud Run's startup + liveness probes point at
         *     ``/health`` (so a transient DB blip never *kills* the instance); its **readiness** probe
         *     points here, so an instance that cannot reach Postgres is pulled from rotation until it
         *     recovers. Any failure answers ``503``, never a ``500`` (wiring these probes into the Cloud
         *     Run service config lands in CD, group 6.6).
         */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/review/due": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Review Due
         * @description Return the user's due batch for a language, split into new vs. previously-reviewed.
         *
         *     The batch size honors the user's per-user ``daily_new_limit`` / ``daily_total_limit``
         *     preferences (read from ``user_settings`` via the settings service — no raw SQL in the router),
         *     each falling back to the ``lengua_core`` config default when unset or invalid.
         */
        get: operations["review_due_review_due_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/review/{card_id}/grade": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Grade Card
         * @description Grade a card (1=Again .. 4=Easy): FSRS reschedule + review log + proficiency nudge.
         */
        post: operations["grade_card_review__card_id__grade_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Settings
         * @description Return all of the current user's settings.
         */
        get: operations["get_settings_settings_get"];
        /**
         * Put Settings
         * @description Upsert (merge) the supplied settings and return the full updated map.
         */
        put: operations["put_settings_settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AccountDeletionAck
         * @description Generic acknowledgement for both public deletion endpoints.
         *
         *     Deliberately identical whether or not an account exists / the mail was sent, so the response
         *     never discloses whether an email is registered (no account enumeration).
         */
        AccountDeletionAck: {
            /** Message */
            message: string;
            /** Status */
            status: string;
        };
        /**
         * AccountDeletionConfirm
         * @description Body of ``POST /account/deletion-confirm`` — the signed token from the emailed link.
         */
        AccountDeletionConfirm: {
            /** Token */
            token: string;
        };
        /**
         * AccountDeletionRequest
         * @description Body of ``POST /account/deletion-request`` — the email to send a deletion link to.
         */
        AccountDeletionRequest: {
            /** Email */
            email: string;
        };
        /**
         * AccountExport
         * @description The complete export bundle for one user — everything owned by ``current_user``.
         *
         *     ``profile`` is ``None`` only for a token-only identity whose ``profiles`` row does not exist
         *     yet (e.g. mid-trigger); a real signed-up user always has one.
         */
        AccountExport: {
            /** Cards */
            cards: components["schemas"]["CardExport"][];
            /** Languages */
            languages: components["schemas"]["LanguageExport"][];
            /** Proficiency */
            proficiency: components["schemas"]["ProficiencyExport"][];
            profile?: components["schemas"]["ProfileExport"] | null;
            /** Reviews */
            reviews: components["schemas"]["ReviewExport"][];
            /** Settings */
            settings: {
                [key: string]: string | null;
            };
        };
        /**
         * CardExport
         * @description One flashcard, with its full scheduling/generation state preserved.
         */
        CardExport: {
            /** Back */
            back: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Direction */
            direction?: string | null;
            /** Due */
            due?: string | null;
            /** Front */
            front: string;
            /** Fsrs State */
            fsrs_state?: {
                [key: string]: unknown;
            } | null;
            /** Gen Level */
            gen_level?: number | null;
            /** Id */
            id: number;
            /** Language Id */
            language_id: number;
            /** Saved */
            saved: boolean;
            /** Used Words */
            used_words?: string[] | null;
            /** Word Explanations */
            word_explanations?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * CardOut
         * @description A persisted flashcard row as returned by the API.
         */
        CardOut: {
            /** Back */
            back: string;
            /** Direction */
            direction: string | null;
            /** Due */
            due: string | null;
            /** Front */
            front: string;
            /** Gen Level */
            gen_level: number | null;
            /** Id */
            id: number;
            /** Language Id */
            language_id: number;
            /** Saved */
            saved: boolean;
            /** Used Words */
            used_words: string[] | null;
            /** Word Explanations */
            word_explanations: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * DiscoverAcceptRequest
         * @description Request body for ``POST /discover/accept`` — turn accepted words into saved cards.
         */
        DiscoverAcceptRequest: {
            /** Language Id */
            language_id: number;
            /** Words */
            words: string[];
        };
        /**
         * DiscoverRequest
         * @description Request body for ``POST /discover`` — preview new vocabulary.
         */
        DiscoverRequest: {
            /**
             * Count
             * @default 5
             */
            count: number;
            /**
             * Fresh
             * @default false
             */
            fresh: boolean;
            /** Language Id */
            language_id: number;
            /** Topic */
            topic?: string | null;
        };
        /**
         * DiscoverResponse
         * @description The preview: new words the learner does not already have a card for.
         */
        DiscoverResponse: {
            /** Words */
            words: string[];
        };
        /**
         * DueResponse
         * @description The due batch for a language, split into never-reviewed (``new``) vs. ``due`` cards.
         */
        DueResponse: {
            /** Due */
            due: components["schemas"]["CardOut"][];
            /** New */
            new: components["schemas"]["CardOut"][];
        };
        /**
         * ExplainRequest
         * @description Request body for ``POST /explain`` — a tapped word in a card's sentence.
         *
         *     ``sentence`` is the target-language sentence (the production card's back) and ``translation``
         *     its English gloss, mirroring ``lengua_core.gemini.explain_word`` so any provider is a drop-in.
         */
        ExplainRequest: {
            /** Language Id */
            language_id: number;
            /** Sentence */
            sentence: string;
            /** Translation */
            translation: string;
            /** Word */
            word: string;
        };
        /**
         * ExplainResponse
         * @description A short explanation of the tapped word (served from the card's cache when available).
         */
        ExplainResponse: {
            /** Explanation */
            explanation: string;
            /** Word */
            word: string;
        };
        /**
         * GenerateRequest
         * @description Request body for ``POST /generate``.
         */
        GenerateRequest: {
            /** Language Id */
            language_id: number;
            /** Words */
            words?: string[];
        };
        /**
         * GeneratedCardModel
         * @description One built (unsaved) flashcard direction — a generate preview / a save input item.
         */
        GeneratedCardModel: {
            /** Back */
            back: string;
            /** Direction */
            direction: string;
            /** Front */
            front: string;
            /** Gen Level */
            gen_level?: number | null;
            /** Used Words */
            used_words: string[];
            /** Word Explanations */
            word_explanations?: {
                [key: string]: string;
            } | null;
        };
        /**
         * GradeRequest
         * @description Request body for ``POST /review/{card_id}/grade`` — an FSRS rating 1..4.
         */
        GradeRequest: {
            /** Rating */
            rating: number;
        };
        /**
         * GradeResponse
         * @description The outcome of grading a card.
         */
        GradeResponse: {
            /** Card Id */
            card_id: number;
            /**
             * Due
             * Format: date-time
             */
            due: string;
            /** Score */
            score: number;
            /** Score Changed */
            score_changed: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LanguageCreate
         * @description Request body for ``POST /languages``.
         */
        LanguageCreate: {
            /** Code */
            code?: string | null;
            /** Name */
            name: string;
            /**
             * Vowelized
             * @default false
             */
            vowelized: boolean;
        };
        /**
         * LanguageCreateOut
         * @description ``POST /languages`` response: the language plus whether THIS request created it.
         *
         *     ``created`` is ``True`` when a new language was inserted and ``False`` when the name already
         *     existed — an idempotent add, where the existing row is returned **unchanged**. It lets the
         *     client tell a fresh add from a re-add, so re-adding an existing language never resets its
         *     recorded proficiency (finding S3). Returned with HTTP 200 (the API's convention for ``POST``),
         *     so the flag — not the status code — carries the created/existing signal.
         */
        LanguageCreateOut: {
            /** Code */
            code: string | null;
            /** Created */
            created: boolean;
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Vowelized */
            vowelized: boolean;
        };
        /**
         * LanguageExport
         * @description One language the user studies.
         */
        LanguageExport: {
            /** Code */
            code?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Vowelized */
            vowelized: boolean;
        };
        /**
         * LanguageLevel
         * @description One of the user's languages with its current proficiency level.
         */
        LanguageLevel: {
            /** Band */
            band: string;
            /** Code */
            code?: string | null;
            /** Language Id */
            language_id: number;
            /** Name */
            name: string;
            /** Progress */
            progress: number;
            /** Score */
            score: number;
        };
        /**
         * LanguageOut
         * @description A language as returned by the API.
         */
        LanguageOut: {
            /** Code */
            code: string | null;
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Vowelized */
            vowelized: boolean;
        };
        /**
         * LanguageUpdate
         * @description Request body for ``PATCH /languages/{id}`` — a partial update of the editable fields.
         *
         *     Every field is optional; only the ones actually present in the request body are applied (the
         *     route reads ``model_dump(exclude_unset=True)``), so a client can rename a language, set or clear
         *     its ``code``, or toggle ``vowelized`` independently. ``code`` may be sent as ``null`` to clear
         *     it. Making ``name``/``code`` editable lets a user fix a mistyped name or a missing/blank code
         *     after creation — e.g. to give a right-to-left language its ``he``/``ar`` code so its script
         *     renders (direction + diacritic-correct font) correctly.
         */
        LanguageUpdate: {
            /** Code */
            code?: string | null;
            /** Name */
            name?: string | null;
            /** Vowelized */
            vowelized?: boolean | null;
        };
        /**
         * MeOut
         * @description The authenticated user's account overview (identity + plan + per-language levels).
         */
        MeOut: {
            /** Email */
            email?: string | null;
            /** Email Verified */
            email_verified: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Languages */
            languages: components["schemas"]["LanguageLevel"][];
            /** Plan */
            plan: string;
        };
        /**
         * ProficiencyExport
         * @description The user's continuous proficiency score for one language.
         */
        ProficiencyExport: {
            /** Language Id */
            language_id: number;
            /** Score */
            score: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ProficiencyOut
         * @description A learner's level for one language: continuous score, CEFR band, intra-band progress.
         */
        ProficiencyOut: {
            /** Band */
            band: string;
            /** Progress */
            progress: number;
            /** Score */
            score: number;
        };
        /**
         * ProficiencyUpdate
         * @description Request body for ``PUT /proficiency/{language_id}`` — override by score *or* CEFR band.
         *
         *     Exactly one of ``score`` / ``band`` must be supplied; ``score`` is clamped to the valid
         *     range and ``band`` is mapped to that band's lower-bound score by the service.
         */
        ProficiencyUpdate: {
            /** Band */
            band?: string | null;
            /** Score */
            score?: number | null;
        };
        /**
         * ProfileExport
         * @description The user's profile row (account ``plan`` + creation time).
         */
        ProfileExport: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Plan */
            plan: string;
        };
        /**
         * ReviewExport
         * @description One grade event (FSRS rating 1..4) against a card.
         */
        ReviewExport: {
            /** Card Id */
            card_id: number;
            /** Id */
            id: number;
            /** Rating */
            rating: number;
            /**
             * Reviewed At
             * Format: date-time
             */
            reviewed_at: string;
        };
        /**
         * SaveCardsRequest
         * @description Request body for ``POST /cards/save`` — the generate previews to persist.
         */
        SaveCardsRequest: {
            /** Cards */
            cards: components["schemas"]["GeneratedCardModel"][];
            /** Language Id */
            language_id: number;
        };
        /**
         * SettingsOut
         * @description All of the user's settings as a ``{key: value}`` map.
         */
        SettingsOut: {
            /** Values */
            values: {
                [key: string]: string | null;
            };
        };
        /**
         * SettingsUpdate
         * @description Request body for ``PUT /settings`` — upsert (merge) one or more settings.
         *
         *     Only the keys present are written; keys not listed are left untouched. A key mapped
         *     to ``null`` is **removed** (finding S10), so a merge can clear a key, not only set
         *     one — previously a written key could never be deleted through the API. At least one
         *     key must be supplied.
         *
         *     The typed numeric keys (``daily_*_limit`` and ``discover_count``) are bounds-checked
         *     server-side in the settings service, which also enforces
         *     ``daily_new_limit <= daily_total_limit`` (finding S9); a violation returns **422**.
         *     That check lives in the service, not this model, so the OpenAPI contract stays neutral.
         */
        SettingsUpdate: {
            /** Values */
            values: {
                [key: string]: string | null;
            };
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    delete_account_account_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    confirm_account_deletion_account_deletion_confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountDeletionConfirm"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountDeletionAck"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_account_deletion_account_deletion_request_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountDeletionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountDeletionAck"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_account_account_export_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountExport"];
                };
            };
        };
    };
    save_cards_cards_save_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveCardsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    discover_discover_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiscoverRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscoverResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accept_discover_accept_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiscoverAcceptRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    explain_explain_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExplainRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExplainResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_feature_flags_feature_flags_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
        };
    };
    generate_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeneratedCardModel"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_languages_languages_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LanguageOut"][];
                };
            };
        };
    };
    add_language_languages_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LanguageCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LanguageCreateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_language_languages__language_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                language_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_language_languages__language_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                language_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LanguageUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LanguageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_me_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
        };
    };
    get_proficiency_proficiency__language_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                language_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProficiencyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_proficiency_proficiency__language_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                language_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProficiencyUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProficiencyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    review_due_review_due_get: {
        parameters: {
            query: {
                language_id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DueResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    grade_card_review__card_id__grade_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                card_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GradeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GradeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_settings_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsOut"];
                };
            };
        };
    };
    put_settings_settings_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
