/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Account
         * @description Hard-delete the authenticated user's account (auth user + cascaded domain data).
         */
        delete: operations["delete_account_account_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/account/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Account
         * @description Return the authenticated user's full data bundle (scoped to ``current_user``).
         */
        get: operations["export_account_account_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cards/save": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Save Cards
         * @description Persist generated recognition+production previews into the current user's deck (saved).
         */
        post: operations["save_cards_cards_save_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/discover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Discover
         * @description Preview new words at the learner's level, excluding vocabulary they already know.
         *
         *     Gated by the per-user daily ``discover`` cap (``quota_guard``) before the provider call.
         */
        post: operations["discover_discover_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/discover/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Accept
         * @description Generate and save cards for the accepted ``words`` (delegates to the generate flow).
         *
         *     Accepting reuses the generate path, so it is gated and counted as ``generate`` (not
         *     ``discover``).
         */
        post: operations["accept_discover_accept_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/explain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Explain
         * @description Explain a tapped word in a sentence (served from the card's cache when available).
         *
         *     The ``guard`` is built **unchecked** and handed to ``ExplainService`` so the per-user daily
         *     ``explain`` cap is enforced (and counted) only on a cache miss — a cache hit stays free.
         */
        post: operations["explain_explain_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate
         * @description Generate recognition+production card previews for ``words`` (nothing is persisted yet).
         *
         *     The ``quota_guard`` dependency enforces the per-user daily ``generate`` cap before the provider
         *     is called; on success we count the spend (cache-miss equivalent — generate always calls).
         */
        post: operations["generate_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe used by Cloud Run and CI smoke checks.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/languages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Languages
         * @description List the current user's languages, oldest first.
         */
        get: operations["list_languages_languages_get"];
        put?: never;
        /**
         * Add Language
         * @description Add a language (idempotent on the per-user ``UNIQUE (user_id, name)``).
         */
        post: operations["add_language_languages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/languages/{language_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove Language
         * @description Delete a language (its cards/proficiency cascade).
         */
        delete: operations["remove_language_languages__language_id__delete"];
        options?: never;
        head?: never;
        /**
         * Set Vowelized
         * @description Toggle a language's ``vowelized`` flag.
         */
        patch: operations["set_vowelized_languages__language_id__patch"];
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Me
         * @description Return the authenticated user's identity, plan, and per-language proficiency levels.
         */
        get: operations["read_me_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/proficiency/{language_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Proficiency
         * @description Return the learner's level for one of their languages.
         */
        get: operations["get_proficiency_proficiency__language_id__get"];
        /**
         * Set Proficiency
         * @description Override the level by raw ``score`` or CEFR ``band`` (exactly one; enforced by the DTO).
         */
        put: operations["set_proficiency_proficiency__language_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/review/due": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Review Due
         * @description Return the user's due batch for a language, split into new vs. previously-reviewed.
         */
        get: operations["review_due_review_due_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/review/{card_id}/grade": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Grade Card
         * @description Grade a card (1=Again .. 4=Easy): FSRS reschedule + review log + proficiency nudge.
         */
        post: operations["grade_card_review__card_id__grade_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Settings
         * @description Return all of the current user's settings.
         */
        get: operations["get_settings_settings_get"];
        /**
         * Put Settings
         * @description Upsert (merge) the supplied settings and return the full updated map.
         */
        put: operations["put_settings_settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AccountExport
         * @description The complete export bundle for one user — everything owned by ``current_user``.
         *
         *     ``profile`` is ``None`` only for a token-only identity whose ``profiles`` row does not exist
         *     yet (e.g. mid-trigger); a real signed-up user always has one.
         */
        AccountExport: {
            /** Cards */
            cards: components["schemas"]["CardExport"][];
            /** Languages */
            languages: components["schemas"]["LanguageExport"][];
            /** Proficiency */
            proficiency: components["schemas"]["ProficiencyExport"][];
            profile?: components["schemas"]["ProfileExport"] | null;
            /** Reviews */
            reviews: components["schemas"]["ReviewExport"][];
            /** Settings */
            settings: {
                [key: string]: string | null;
            };
        };
        /**
         * CardExport
         * @description One flashcard, with its full scheduling/generation state preserved.
         */
        CardExport: {
            /** Back */
            back: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Direction */
            direction?: string | null;
            /** Due */
            due?: string | null;
            /** Front */
            front: string;
            /** Fsrs State */
            fsrs_state?: {
                [key: string]: unknown;
            } | null;
            /** Gen Level */
            gen_level?: number | null;
            /** Id */
            id: number;
            /** Language Id */
            language_id: number;
            /** Saved */
            saved: boolean;
            /** Used Words */
            used_words?: string[] | null;
            /** Word Explanations */
            word_explanations?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * CardOut
         * @description A persisted flashcard row as returned by the API.
         */
        CardOut: {
            /** Back */
            back: string;
            /** Direction */
            direction: string | null;
            /** Due */
            due: string | null;
            /** Front */
            front: string;
            /** Gen Level */
            gen_level: number | null;
            /** Id */
            id: number;
            /** Language Id */
            language_id: number;
            /** Saved */
            saved: boolean;
            /** Used Words */
            used_words: string[] | null;
            /** Word Explanations */
            word_explanations: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * DiscoverAcceptRequest
         * @description Request body for ``POST /discover/accept`` — turn accepted words into saved cards.
         */
        DiscoverAcceptRequest: {
            /** Language Id */
            language_id: number;
            /** Words */
            words: string[];
        };
        /**
         * DiscoverRequest
         * @description Request body for ``POST /discover`` — preview new vocabulary.
         */
        DiscoverRequest: {
            /**
             * Count
             * @default 5
             */
            count: number;
            /** Language Id */
            language_id: number;
            /** Topic */
            topic?: string | null;
        };
        /**
         * DiscoverResponse
         * @description The preview: new words the learner does not already have a card for.
         */
        DiscoverResponse: {
            /** Words */
            words: string[];
        };
        /**
         * DueResponse
         * @description The due batch for a language, split into never-reviewed (``new``) vs. ``due`` cards.
         */
        DueResponse: {
            /** Due */
            due: components["schemas"]["CardOut"][];
            /** New */
            new: components["schemas"]["CardOut"][];
        };
        /**
         * ExplainRequest
         * @description Request body for ``POST /explain`` — a tapped word in a card's sentence.
         *
         *     ``sentence`` is the target-language sentence (the production card's back) and ``translation``
         *     its English gloss, mirroring ``lengua_core.gemini.explain_word`` so any provider is a drop-in.
         */
        ExplainRequest: {
            /** Language Id */
            language_id: number;
            /** Sentence */
            sentence: string;
            /** Translation */
            translation: string;
            /** Word */
            word: string;
        };
        /**
         * ExplainResponse
         * @description A short explanation of the tapped word (served from the card's cache when available).
         */
        ExplainResponse: {
            /** Explanation */
            explanation: string;
            /** Word */
            word: string;
        };
        /**
         * GenerateRequest
         * @description Request body for ``POST /generate``.
         */
        GenerateRequest: {
            /** Language Id */
            language_id: number;
            /** Words */
            words?: string[];
        };
        /**
         * GeneratedCardModel
         * @description One built (unsaved) flashcard direction — a generate preview / a save input item.
         */
        GeneratedCardModel: {
            /** Back */
            back: string;
            /** Direction */
            direction: string;
            /** Front */
            front: string;
            /** Gen Level */
            gen_level?: number | null;
            /** Used Words */
            used_words: string[];
            /** Word Explanations */
            word_explanations?: {
                [key: string]: string;
            } | null;
        };
        /**
         * GradeRequest
         * @description Request body for ``POST /review/{card_id}/grade`` — an FSRS rating 1..4.
         */
        GradeRequest: {
            /** Rating */
            rating: number;
        };
        /**
         * GradeResponse
         * @description The outcome of grading a card.
         */
        GradeResponse: {
            /** Card Id */
            card_id: number;
            /**
             * Due
             * Format: date-time
             */
            due: string;
            /** Score */
            score: number;
            /** Score Changed */
            score_changed: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LanguageCreate
         * @description Request body for ``POST /languages``.
         */
        LanguageCreate: {
            /** Code */
            code?: string | null;
            /** Name */
            name: string;
            /**
             * Vowelized
             * @default false
             */
            vowelized: boolean;
        };
        /**
         * LanguageExport
         * @description One language the user studies.
         */
        LanguageExport: {
            /** Code */
            code?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Vowelized */
            vowelized: boolean;
        };
        /**
         * LanguageLevel
         * @description One of the user's languages with its current proficiency level.
         */
        LanguageLevel: {
            /** Band */
            band: string;
            /** Code */
            code?: string | null;
            /** Language Id */
            language_id: number;
            /** Name */
            name: string;
            /** Progress */
            progress: number;
            /** Score */
            score: number;
        };
        /**
         * LanguageOut
         * @description A language as returned by the API.
         */
        LanguageOut: {
            /** Code */
            code: string | null;
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Vowelized */
            vowelized: boolean;
        };
        /**
         * LanguageUpdate
         * @description Request body for ``PATCH /languages/{id}`` — toggle the ``vowelized`` flag.
         */
        LanguageUpdate: {
            /** Vowelized */
            vowelized: boolean;
        };
        /**
         * MeOut
         * @description The authenticated user's account overview (identity + plan + per-language levels).
         */
        MeOut: {
            /** Email */
            email?: string | null;
            /** Email Verified */
            email_verified: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Languages */
            languages: components["schemas"]["LanguageLevel"][];
            /** Plan */
            plan: string;
        };
        /**
         * ProficiencyExport
         * @description The user's continuous proficiency score for one language.
         */
        ProficiencyExport: {
            /** Language Id */
            language_id: number;
            /** Score */
            score: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ProficiencyOut
         * @description A learner's level for one language: continuous score, CEFR band, intra-band progress.
         */
        ProficiencyOut: {
            /** Band */
            band: string;
            /** Progress */
            progress: number;
            /** Score */
            score: number;
        };
        /**
         * ProficiencyUpdate
         * @description Request body for ``PUT /proficiency/{language_id}`` — override by score *or* CEFR band.
         *
         *     Exactly one of ``score`` / ``band`` must be supplied; ``score`` is clamped to the valid
         *     range and ``band`` is mapped to that band's lower-bound score by the service.
         */
        ProficiencyUpdate: {
            /** Band */
            band?: string | null;
            /** Score */
            score?: number | null;
        };
        /**
         * ProfileExport
         * @description The user's profile row (account ``plan`` + creation time).
         */
        ProfileExport: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Plan */
            plan: string;
        };
        /**
         * ReviewExport
         * @description One grade event (FSRS rating 1..4) against a card.
         */
        ReviewExport: {
            /** Card Id */
            card_id: number;
            /** Id */
            id: number;
            /** Rating */
            rating: number;
            /**
             * Reviewed At
             * Format: date-time
             */
            reviewed_at: string;
        };
        /**
         * SaveCardsRequest
         * @description Request body for ``POST /cards/save`` — the generate previews to persist.
         */
        SaveCardsRequest: {
            /** Cards */
            cards: components["schemas"]["GeneratedCardModel"][];
            /** Language Id */
            language_id: number;
        };
        /**
         * SettingsOut
         * @description All of the user's settings as a ``{key: value}`` map.
         */
        SettingsOut: {
            /** Values */
            values: {
                [key: string]: string | null;
            };
        };
        /**
         * SettingsUpdate
         * @description Request body for ``PUT /settings`` — upsert (merge) one or more settings.
         *
         *     Only the keys present are written; existing keys not listed are left untouched.
         */
        SettingsUpdate: {
            /** Values */
            values: {
                [key: string]: string;
            };
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    delete_account_account_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    export_account_account_export_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountExport"];
                };
            };
        };
    };
    save_cards_cards_save_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveCardsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    discover_discover_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiscoverRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscoverResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accept_discover_accept_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiscoverAcceptRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    explain_explain_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExplainRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExplainResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeneratedCardModel"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_languages_languages_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LanguageOut"][];
                };
            };
        };
    };
    add_language_languages_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LanguageCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LanguageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_language_languages__language_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                language_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_vowelized_languages__language_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                language_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LanguageUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LanguageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_me_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
        };
    };
    get_proficiency_proficiency__language_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                language_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProficiencyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_proficiency_proficiency__language_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                language_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProficiencyUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProficiencyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_due_review_due_get: {
        parameters: {
            query: {
                language_id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DueResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    grade_card_review__card_id__grade_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                card_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GradeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GradeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_settings_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsOut"];
                };
            };
        };
    };
    put_settings_settings_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
